default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <% if ENV["DB_HOST"] %>
  host: <%= ENV["DB_HOST"] %>
  username: postgres
  password: postgres
  <% else %>
  host: host.docker.internal
  username: postgres
  <% end %>

development:
  <<: *default
  database: vtfbackend_development

test:
  <<: *default
  database: vtfbackend_test

production:
  <<: *default
  database: vtfbackend_production
  url: <%= ENV['DATABASE_URL'] %>