default: &default
  dispatchers: []  # No hay despachadores
  workers: []      # No hay trabajadores

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default  # No hay configuraciones específicas para producción, usa las del default.