# .github/workflows/deploy.yml
name: Deploy to Elastic Beanstalk
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create ZIP deployment package
        run: |
          git archive -v -o deploy.zip --format=zip HEAD
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Upload package to S3 bucket
        run: |
          aws s3 cp deploy.zip s3://${{ secrets.EB_BUCKET }}/deploy.zip
          
      - name: Create new Elastic Beanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ secrets.EB_APPLICATION }} \
          --version-label "ver-${{ github.sha }}" \
          --source-bundle S3Bucket="${{ secrets.EB_BUCKET }}",S3Key="deploy.zip"
          
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
          --environment-name ${{ secrets.EB_ENVIRONMENT }} \
          --version-label "ver-${{ github.sha }}"